### ISSUE TITLE
bug in WSL2 on windows in latest release

### ISSUE THREAD

**Issue by Dmitry1987** [superbrothers/kubectl-view-kubeconfig-plugin#74]
Hi guys I think there's a bug, I run in WSL2 and it shows this

```
kubectl view-serviceaccount-kubeconfig default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14622b9]

goroutine 1 [running]:
github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/pkg/cmd.(*ViewServiceaccountKubeconfigOptions).Run(0xc000124d20)  
        /home/runner/work/kubectl-view-serviceaccount-kubeconfig-plugin/kubectl-view-serviceaccount-kubeconfig-plugin/pkg/cmd/view-serviceaccount-kubeconfig.go:159 +0x119
github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/pkg/cmd.NewCmdViewServiceaccountKubeconfig.func1(0xc00041e300, {0xc000430e40?, 0x4?, 0x1788c19?})
        /home/runner/work/kubectl-view-serviceaccount-kubeconfig-plugin/kubectl-view-serviceaccount-kubeconfig-plugin/pkg/cmd/view-serviceaccount-kubeconfig.go:96 +0x45
github.com/spf13/cobra.(*Command).execute(0xc00041e300, {0xc00012a010, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00041e300)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x19dbda0?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
        /home/runner/work/kubectl-view-serviceaccount-kubeconfig-plugin/kubectl-view-serviceaccount-kubeconfig-plugin/cmd/kubectl-view_serviceaccount_kubeconfig.go:25 +0xf5
```

version is:

```
kubectl krew list
PLUGIN                          VERSION
krew                            v0.4.4
view-serviceaccount-kubeconfig  v2.3.1
```

**Comment by Nabsku** [comment]
Do you have a working/active kubeconfig? This only happened to me when there was no kubeconfig present. Albeit this shouldn't throw an error like this.. :)
